package com.smartcurriculum.portal.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * DTO for exposing Activity data to API clients.
 */
public class ActivityResponseDto {
    private Long id;
    private String activityCode;
    private String title;
    private String description;
    private String activityType;
    private String department;
    private String academicYear;
    private Integer semester;
    private Integer credits;
    private String venue;
    private Long facultyId;
    private LocalDate startDate;
    private LocalDate endDate;
    private Integer maxEnrollment;
    private String status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public static ActivityResponseDto fromEntity(com.smartcurriculum.portal.entity.Activity activity) {
        ActivityResponseDto dto = new ActivityResponseDto();
        dto.id = activity.getId();
        dto.activityCode = activity.getActivityCode();
        dto.title = activity.getTitle();
        dto.description = activity.getDescription();
        dto.activityType = activity.getActivityType();
        dto.department = activity.getDepartment();
        dto.academicYear = activity.getAcademicYear();
        dto.semester = activity.getSemester();
        dto.credits = activity.getCredits();
        dto.venue = activity.getVenue();
        dto.facultyId = activity.getFaculty() != null ? activity.getFaculty().getId() : null;
        dto.startDate = activity.getStartDate();
        dto.endDate = activity.getEndDate();
        dto.maxEnrollment = activity.getMaxEnrollment();
        dto.status = activity.getStatus();
        dto.createdAt = activity.getCreatedAt();
        dto.updatedAt = activity.getUpdatedAt();
        return dto;
    }

    // Getters and setters (omitted for brevity; can be generated by IDE)
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getActivityCode() { return activityCode; }
    public void setActivityCode(String activityCode) { this.activityCode = activityCode; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getActivityType() { return activityType; }
    public void setActivityType(String activityType) { this.activityType = activityType; }
    public String getDepartment() { return department; }
    public void setDepartment(String department) { this.department = department; }
    public String getAcademicYear() { return academicYear; }
    public void setAcademicYear(String academicYear) { this.academicYear = academicYear; }
    public Integer getSemester() { return semester; }
    public void setSemester(Integer semester) { this.semester = semester; }
    public Integer getCredits() { return credits; }
    public void setCredits(Integer credits) { this.credits = credits; }
    public String getVenue() { return venue; }
    public void setVenue(String venue) { this.venue = venue; }
    public Long getFacultyId() { return facultyId; }
    public void setFacultyId(Long facultyId) { this.facultyId = facultyId; }
    public LocalDate getStartDate() { return startDate; }
    public void setStartDate(LocalDate startDate) { this.startDate = startDate; }
    public LocalDate getEndDate() { return endDate; }
    public void setEndDate(LocalDate endDate) { this.endDate = endDate; }
    public Integer getMaxEnrollment() { return maxEnrollment; }
    public void setMaxEnrollment(Integer maxEnrollment) { this.maxEnrollment = maxEnrollment; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
